In [1]:
import numpy as np

- np.array()         : create an array in NumPy.
- np.arange()        : create an array with a range of values.
- np.zeros()         : create an array filled with zeros.
- np.ones()          : create an array filled with ones.
- np.linspace()      : create an array with a specified number of evenly spaced values.
- np.random.rand()   : create an array with random values between 0 and 1.
- np.random.randint(): create an array with random integer values between a specified range.
- np.max()           : return the maximum value in numpy array
- np.min()           : return the minimum value in numpy array
- np.mean()          : return the mean/average of in numpy array values
- np.delete()        : return the new array after deleting the value at given index
- np.dot()           : return the dot product of two arrays.
- np.sum()           : return the sum of all element of the array
- np.prod()          : return the product of all elments of the array two arrays.
- np.nansum()        : return the sum of all element of the array considering nan value as zero 
- np.nanprod()       : return the product of all element of the array considering nan value as one    
- numpy.reshape()    : returns the array in the given shape
- numpy.concatenate(): return the array after join

#### SUM/ NANSUM

In [60]:
a = np.arange(11);
print(f'SUM : {np.sum(a)}')

SUM : 55


In [61]:
a = np.array([1,2,3,4,5,np.nan])
print(f'SUM : {np.sum(a)}')
print(f'NaNSUM : {np.nansum(a)}')

SUM : nan
NaNSUM : 15.0


#### Prod/ NANProd

In [62]:
a = np.arange(3,7);
print(a)
print(f'Product : {np.prod(a)}')

[3 4 5 6]
Product : 360


In [63]:
a = np.array([1,2,3,4,5,np.nan])
print(f'Product : {np.prod(a)}')
print(f'NaNProduct : {np.nanprod(a)}')

Product : nan
NaNProduct : 120.0


#### Array Function:

In [7]:
#Array Function:
a = np.array([1,2,3,4,5], dtype=np.int64)
print(f'Dimention of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 1 D Array
Shape of the Array     : (5,)
Element of the Array   : [1 2 3 4 5]


#### Arange Function

In [8]:
#range(start=0,end,step=1)
for index in range(10,100,5):
    print(index,end=',')

10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,

In [11]:
#help(np.arange)

In [9]:
a = np.arange(10)
print(f'Dimention of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 1 D Array
Shape of the Array     : (10,)
Element of the Array   : [0 1 2 3 4 5 6 7 8 9]


In [15]:
# np.arange(start,stop,step)
a = np.arange(5,100,5)
print(f'Dimention of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 1 D Array
Shape of the Array     : (19,)
Element of the Array   : [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


#### Zeros Functions

In [17]:
#help(np.zeros)

In [18]:
# One Dimension array creation with 0 as all elements
a = np.zeros(10)
print(f'Dimension of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 1 D Array
Shape of the Array     : (10,)
Element of the Array   : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
# Two Dimension array creation with 0 as all elements (4,5) => 4 one D array, each array has 5 element
a = np.zeros((4,5),dtype=np.int64)
print(f'Dimention of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 2 D Array
Shape of the Array     : (4, 5)
Element of the Array   : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### Ones Functions

In [25]:
#help(np.ones)

In [26]:
# One Dimension array creation with 1 as all elements
a = np.ones(10)
print(f'Dimension of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimension of the Array : 1 D Array
Shape of the Array     : (10,)
Element of the Array   : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# Two Dimension array creation with 1 as all elements (4,5) => 4 one D array, each array has 5 element
a = np.ones((4,5),dtype=np.int64)
print(f'Dimention of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimention of the Array : 2 D Array
Shape of the Array     : (4, 5)
Element of the Array   : [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Linspace

In [29]:
#help(np.linspace)
0 to 99 : 101 data points

In [39]:
a = np.linspace(0,100,100)
print(f'Dimension of the Array : {a.ndim} D Array')
print(f'Shape of the Array     : {a.shape}')
print(f'Element of the Array   : {a}')

Dimension of the Array : 1 D Array
Shape of the Array     : (100,)
Element of the Array   : [  0.           1.01010101   2.02020202   3.03030303   4.04040404
   5.05050505   6.06060606   7.07070707   8.08080808   9.09090909
  10.1010101   11.11111111  12.12121212  13.13131313  14.14141414
  15.15151515  16.16161616  17.17171717  18.18181818  19.19191919
  20.2020202   21.21212121  22.22222222  23.23232323  24.24242424
  25.25252525  26.26262626  27.27272727  28.28282828  29.29292929
  30.3030303   31.31313131  32.32323232  33.33333333  34.34343434
  35.35353535  36.36363636  37.37373737  38.38383838  39.39393939
  40.4040404   41.41414141  42.42424242  43.43434343  44.44444444
  45.45454545  46.46464646  47.47474747  48.48484848  49.49494949
  50.50505051  51.51515152  52.52525253  53.53535354  54.54545455
  55.55555556  56.56565657  57.57575758  58.58585859  59.5959596
  60.60606061  61.61616162  62.62626263  63.63636364  64.64646465
  65.65656566  66.66666667  67.67676768  68.6868686

In [41]:
a = np.linspace(0,100,100,endpoint=True,retstep=True)
print(f'Step Size: from 0 to 100 : {a[1]}')
a = np.linspace(0,100,100,endpoint=False,retstep=True)
print(f'Step Size: from 0 to 99 : {a[1]}')

Step Size: from 0 to 100 : 1.0101010101010102
Step Size: from 0 to 99 : 1.0


#### Random.rand

In [53]:
#help(np.random.rand)

In [54]:
# if we don't paas shape, then it generates the random value between 0 to 1
a = np.random.rand()
print(a)

0.25583123760786863


In [55]:
# If will generate numpy array with random value according to shape passed
a = np.random.rand(4,2)
print(a)

[[0.64884607 0.4437386 ]
 [0.38037357 0.37494847]
 [0.61404426 0.65055418]
 [0.88764074 0.40544633]]


#### Random.randint

In [57]:
#help(np.random.randint)
#np.linspace(low,high=None,size=None,dtype=int)

In [63]:
# if we don't paas shape, then it generates the random value between low=5,high=None, [low,high]
for i in range(100):
    a = np.random.randint(5)
    print(a,end=',')

4,4,4,0,2,0,1,3,4,3,4,2,2,2,4,3,3,3,0,1,1,0,0,3,4,0,0,2,0,0,4,0,0,1,4,1,2,3,3,0,3,3,0,2,4,1,3,3,0,1,2,0,4,3,1,0,1,3,1,0,1,4,3,4,4,3,3,3,4,2,0,3,3,1,0,4,4,1,0,0,1,3,2,1,4,1,3,4,2,3,1,0,1,3,0,1,4,4,1,4,

In [66]:
for i in range(100):
    # [low,high) = inclusive of low, and exculsive of high
    a = np.random.randint(5,100)
    print(a,end=',')

68,81,82,26,55,70,94,63,90,72,54,32,87,57,53,83,52,22,43,64,36,90,20,49,9,68,5,50,12,76,42,90,11,21,81,29,67,85,65,81,32,81,81,78,94,38,8,22,88,73,22,87,28,45,79,16,42,37,78,89,17,39,69,46,64,56,46,10,16,29,29,67,11,88,43,39,38,37,27,85,41,88,15,81,8,68,86,53,56,22,47,87,97,77,65,25,97,42,35,22,

In [69]:
# if size is defined as tuple shape, it will return the matrix with that size with random integer value between [low,high)
a = np.random.randint(5,100,size=(3,4))
print(a)

[[66 71 80 38]
 [93 93 97 93]
 [16 53 92 62]]


In [74]:
a = np.random.randint(10,1000,size=(10,10))

#### Max Function

In [75]:
print(f'Max Value in Array : {np.max(a)}')

Max Value in Array : 990


#### Min Function

In [76]:
print(f'Min Value in Array : {np.min(a)}')

Min Value in Array : 42


#### Mean Function

In [77]:
print(f'Mean Value in Array : {np.mean(a)}')

Mean Value in Array : 528.06


#### Median Function

In [104]:
a = np.random.randint(10,1000,size=(12))
print(a)

[888 432 123 822 207 817 716 735 505 537 694 296]


In [108]:
l = [888, 432, 123, 822, 207, 817, 716, 735,505, 537, 694, 296]
l.sort()
print(l)
if len(l)%2 == 1:
    print(f'Median is {int((len(l)+1)/2)} term : {l[int((len(l)+1)/2)-1]}')
else:
    print(f'Median is {int(len(l)/2)} term and {int(len(l)/2)+1} term : {(l[int(len(l)/2)-1] + l[int(len(l)/2)])/2}')
    

[123, 207, 296, 432, 505, 537, 694, 716, 735, 817, 822, 888]
Median is 6 term and 7 term : 615.5


In [107]:
"""
Odd: Median = [(n + 1)/2]th term
Even: Median = [(n/2)th term + (n/2 + 1)th term]/2
"""
print(f'Mean/Average Value in Array  : {np.mean(a)}')
print(f'Median Value in Array        : {np.median(a)}')

Mean/Average Value in Array  : 564.3333333333334
Median Value in Array        : 615.5


### Delete Function

In [2]:
import numpy as np
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [9]:
a1 = np.array([1,23,4,56,7,89,34])
print(f'Array a1 [{id(a1)}] : {a1} ')

Array a1 [4393226896] : [ 1 23  4 56  7 89 34] 


In [10]:
a2 = np.delete(a1, 0)
print(f'Array a2 [{id(a2)}] : {a2} ')
print(f'Array a1 [{id(a1)}] : {a1} ')

Array a2 [4395588784] : [23  4 56  7 89 34] 
Array a1 [4393226896] : [ 1 23  4 56  7 89 34] 


In [13]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'Array arr [{id(arr)}] :\n{arr}')

Array arr [4390657296] :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
# axis = 0 : row wise
# axis = 1 : column wise
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [18]:
np.delete(arr, 1, 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [24]:
np.delete(arr, [1,3,5,7,9], None)
# reshape the array into one-D and delete index value as 1, 3, 5
#[ 1  2  3  4 5  6  7  8 9 10 11 12]

array([ 1,  3,  5,  7,  9, 11, 12])

In [29]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
# numpy nicer way of slicing
np.delete(arr, np.s_[::2], axis=0)

array([[5, 6, 7, 8]])

In [28]:
# numpy nicer way of slicing
np.delete(arr, np.s_[::2], axis=1)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [31]:
# numpy nicer way of slicing
# axis = None, it will convert array into 1-D and perform the deletion
# [ 1,  2,  3,  4, 5,  6,  7,  8, 9, 10, 11, 12]])
np.delete(arr, np.s_[::2], None)

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
#1 arr[start:end:step]
#2 arr, np.s_[start=0:end=length of array:step=1]
l[::-1]

In [25]:
np.s_[start=0:end=length of the array :2]

slice(None, None, 2)

#### Dot Product : Compute dot product of Two Matrix

In [114]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [115]:
c = np.dot(2,3)
print(c)

6


In [32]:
# Dot product of Single Dimension Array
# Result = 20*1 + 21*2 + 22*3 + 23*4 + 24*5 = 340
a = np.arange(1,6)
print(a)

b = np.arange(20,25)
print(b)

c =  np.dot(a,b)
print(c)

[1 2 3 4 5]
[20 21 22 23 24]
340


In [33]:
# Dot product of Two Dimension Array

# Matrix multipication works : 
# A(m,n) and B (m,n) shape : we can't multiply these matrix 
# column in A matrix is not equal to rows in B Matrix
"""
Codition for matrix multipcation is First matrix column should be 
same number as number of rows in second matrix

Take Row from First MAtrix and Muliply in column in second matrix = sing value
A(3,2) x B(2,3)    = Result matrix dimension C(3,3)
A(4,4)  x B(4,4)   = Result matrix dimension C(4,4)
A(1,5)  x B(5,1)   = Result matrix dimension C(1,1)

[3 1]  x    [5 5]       =     [3*5+1*7   3*5+1*9]      = [22 24]
[1 3]       [7 9]             [1*5+3*7   1*5+3*9]        [26 32]
"""

#First Matrix Row is taken and multiply by second matrix column wise
# Result = Matrix 
a = np.random.randint(1,10,size=(2,2))
print(f'\nMatrix A :\n{a}')

b = np.random.randint(4,10,size=(2,2))
print(f'\nMatrix B :\n{b}')

c =  np.dot(a,b)
print(f'\nMatrix C :\n{c}')


Matrix A :
[[7 6]
 [4 9]]

Matrix B :
[[4 8]
 [6 6]]

Matrix C :
[[64 92]
 [70 86]]


In [35]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
print(f'Matrix of A :\n{a}')

Matrix of A :
[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200

In [6]:
np.arange(3*4*5*6).reshape(3,4,5,6) 
# 3 * 3 D Array, 4 * 2D array, 5 * 1D Array, 6 number of element in 1 D Array

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
      

In [17]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [38]:
b = np.arange(3*4*5*6)[::-1].reshape(5,4,6,3)
print(b)

[[[[359 358 357]
   [356 355 354]
   [353 352 351]
   [350 349 348]
   [347 346 345]
   [344 343 342]]

  [[341 340 339]
   [338 337 336]
   [335 334 333]
   [332 331 330]
   [329 328 327]
   [326 325 324]]

  [[323 322 321]
   [320 319 318]
   [317 316 315]
   [314 313 312]
   [311 310 309]
   [308 307 306]]

  [[305 304 303]
   [302 301 300]
   [299 298 297]
   [296 295 294]
   [293 292 291]
   [290 289 288]]]


 [[[287 286 285]
   [284 283 282]
   [281 280 279]
   [278 277 276]
   [275 274 273]
   [272 271 270]]

  [[269 268 267]
   [266 265 264]
   [263 262 261]
   [260 259 258]
   [257 256 255]
   [254 253 252]]

  [[251 250 249]
   [248 247 246]
   [245 244 243]
   [242 241 240]
   [239 238 237]
   [236 235 234]]

  [[233 232 231]
   [230 229 228]
   [227 226 225]
   [224 223 222]
   [221 220 219]
   [218 217 216]]]


 [[[215 214 213]
   [212 211 210]
   [209 208 207]
   [206 205 204]
   [203 202 201]
   [200 199 198]]

  [[197 196 195]
   [194 193 192]
   [191 190 189]
   [188 1

In [39]:
print(a.shape)

(3, 4, 5, 6)


In [40]:
print(b.shape)

(5, 4, 6, 3)


In [42]:
# Dot product
c = np.dot(a,b)
c.shape

(3, 4, 5, 5, 4, 3)

#### Reshape Function

In [78]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
a.reshape((8,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [80]:
a.reshape((4,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [81]:
a.reshape((2,2,2,3))

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [82]:
a.reshape((1,1,1,2,2,2,3))

array([[[[[[[ 0,  1,  2],
            [ 3,  4,  5]],

           [[ 6,  7,  8],
            [ 9, 10, 11]]],


          [[[12, 13, 14],
            [15, 16, 17]],

           [[18, 19, 20],
            [21, 22, 23]]]]]]])

#### Concatenate

In [97]:
a = np.arange(4,16).reshape(4,3)
b = np.arange(24,30).reshape(2,3)
print(a)
print(b)
c = np.concatenate((a,b),axis=0)
print(c)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[24 25 26]
 [27 28 29]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [24 25 26]
 [27 28 29]]


In [98]:
a = np.arange(4,16).reshape(4,3)
b = np.arange(24,28).reshape(4,1)
print(a)
print(b)
c = np.concatenate((a,b),axis=1)
print(c)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[24]
 [25]
 [26]
 [27]]
[[ 4  5  6 24]
 [ 7  8  9 25]
 [10 11 12 26]
 [13 14 15 27]]


In [99]:
#help(np.concatenate)

In [102]:
a = np.random.randint(100,size=(4,4))
a

array([[32, 89, 17, 73],
       [44, 94,  2, 11],
       [ 7, 59, 52, 37],
       [42, 77, 80, 20]])

In [106]:
#### Broadcasting

In [107]:
c= a + np.arange(4)

array([[32, 90, 19, 76],
       [44, 95,  4, 14],
       [ 7, 60, 54, 40],
       [42, 78, 82, 23]])

#### Masking

In [105]:
a[a<50]

array([32, 17, 44,  2, 11,  7, 37, 42, 20])

In [111]:
a = np.random.randint(100,size=100)
a

array([37, 80, 74, 50, 72, 88, 31, 52, 90, 30, 18, 83, 15, 63, 20, 29, 86,
       65,  7, 56, 80, 94, 90, 23,  1, 25, 99, 44, 15, 93, 69, 65, 98, 71,
       29, 44, 23, 10, 99, 46, 63,  6, 90, 20, 17, 40, 44, 93,  6, 72, 54,
       65, 38, 62, 62, 12, 86,  8, 85, 51, 69, 44, 24, 33, 77, 20, 27, 11,
       41,  5, 55, 11, 16, 15, 44, 68, 43, 31, 17, 19, 70,  3, 39, 23, 21,
       71, 11, 41, 84, 97, 47, 87, 88, 90, 52, 43, 26, 65, 38, 10])

In [ ]:
# Fancy way of accesingf the 1-D List

In [113]:
a[[1,5,10,11,19,32]]

array([80, 88, 18, 83, 56, 98])