### IMPORT the module Numpy

In [2]:
#Method 1

import numpy as np # Creating an alias (short form for writing)

In [3]:
#Method 2
from numpy import *

In [20]:
# How to create an Numpy array
a = np.array([1,2,3,5,56,65])

In [21]:
print(a)

[ 1  2  3  5 56 65]


In [22]:
print(f'Type of Object: {type(a)}')

Type of Object: <class 'numpy.ndarray'>


In [25]:
print(f'Data type for which array was created : {type(a[0])}')

Data type for which array was created : <class 'numpy.int64'>


In [26]:
b = np.array([1,2,3,5,56,65], dtype=np.float64)

In [28]:
print(f'Data type for which array was created : {type(b[0])}')

Data type for which array was created : <class 'numpy.float64'>


In [13]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [31]:
c = np.array((1,2,56,67,98))

In [30]:
type(c)

numpy.ndarray

In [34]:
d = np.array({1,2,56,67,2,98})

In [35]:
type(d)

numpy.ndarray

In [36]:
print(d)

{1, 2, 67, 98, 56}


In [38]:
e = np.array((1,2,56,"rt",67,98))

In [39]:
type(e)

numpy.ndarray

In [40]:
print(e)

['1' '2' '56' 'rt' '67' '98']


In [41]:
f = np.array((1,2,56,56.7, "yt",67,98))

In [42]:
print(f)

['1' '2' '56' '56.7' 'yt' '67' '98']


In [43]:
type(f[0])

numpy.str_

In [44]:
f.ndim

1

### NDimn : ndarray creation for various dimensions

#### 0-d Array

In [46]:
a= np.array(45)

In [51]:
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Array : {a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 0 d array
Array : 45


In [ ]:
#### 1-d Array

In [52]:
a= np.array([45,56,78])

In [53]:
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Array : {a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 1 d array
Array : [45 56 78]


#### 2d array

In [56]:
a= np.array([[45,56],[78,56]],dtype=np.int64)

In [58]:
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 2 d array
Array :
[[45 56]
 [78 56]]


In [8]:
a= np.array([ [45,56,78,56],[67,56,56,76] ],dtype=np.int64)
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 2 d array
Shape of the Array: (2, 4)
Array :
[[45 56 78 56]
 [67 56 56 76]]


In [9]:
a.shape

(2, 4)

In [10]:
a.reshape(4,2)

array([[45, 56],
       [78, 56],
       [67, 56],
       [56, 76]])

### 3-D array

In [79]:
a = np.array( [[[45,56,87,76],[87,21,43,98]], [[98,78,90,97],[84,65,78,45]]] )

In [80]:
a.shape

(2, 2, 4)

In [89]:
a= a.reshape(2,2,2,2)

In [90]:
a = np.array( [[[45,56,87,76],[87,21,43,98]], [[98,78,90,97],[84,65,78,45]]] )
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 4 d array
Shape of the Array: (2, 2, 2, 2)
Array :
[[[[45 56]
   [87 76]]

  [[87 21]
   [43 98]]]


 [[[98 78]
   [90 97]]

  [[84 65]
   [78 45]]]]


In [ ]:
# Creating n dim array (6)


In [15]:
a = np.array([3,4,5,6,6,8], ndmin= 6)
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 6 d array
Shape of the Array: (1, 1, 1, 1, 1, 6)
Array :
[[[[[[3 4 5 6 6 8]]]]]]


#### Indexing Syntax

In [16]:
a[0,0,0,0,0,0]

3

In [22]:
a[0][0][0][0][0][2]

5

In [23]:
# I want to multiple 3rd element to 6th  element
a[0,0,0,0,0,2] * a[0,0,0,0,0,5]

40

In [24]:
#### Negative Indexing 

l =  [ 45, 2, 65, 23, 89, 78]

        0  1   2   3   4   5 
       -6 -5  -4  -3  -2  -1

In [27]:
l =  [ 45, 2, 65, 23, 89, 78]

65

In [38]:
a= np.array([ [45,56,78,56],[67,56,56,76] ],dtype=np.int64)
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 2 d array
Shape of the Array: (2, 4)
Array :
[[45 56 78 56]
 [67 56 56 76]]


In [41]:
# Positive Slicing :
a[:,1:]

array([[56, 78, 56],
       [56, 56, 76]])

In [42]:
a[0:2,1:]

array([[56, 78, 56],
       [56, 56, 76]])

In [45]:
# Negative Indexing
a[:,-3:]

array([[56, 78, 56],
       [56, 56, 76]])

In [46]:
a[-2:,-3:]

array([[56, 78, 56],
       [56, 56, 76]])

#### Slicing 

    - ListName[start=0:end=-1:step=1]

In [28]:
l[1:5]

[2, 65, 23, 89]

In [32]:
l[-4:-2:1]

[65, 23]

In [31]:

l[-3:-5:-1]


[23, 65]

In [33]:
l[:4]

[45, 2, 65, 23]

In [34]:
l[3:]

[23, 89, 78]

In [47]:
a = np.array( [[[45,56,87,76],[87,21,43,98]], [[98,78,90,97],[84,65,78,45]]] )
print(f'Type of array     :" {type(a)}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

Type of array     :" <class 'numpy.ndarray'>
Type of Dimension :" 3 d array
Shape of the Array: (2, 2, 4)
Array :
[[[45 56 87 76]
  [87 21 43 98]]

 [[98 78 90 97]
  [84 65 78 45]]]


In [51]:
a[:,:,0:2] 

array([[[45, 56],
        [87, 21]],

       [[98, 78],
        [84, 65]]])

In [77]:
"""
NEgative Slicing of  

[[[45 56 87 76]
  [87 21 43 98]]
 [[98 78 90 97]
  [84 65 78 45]]]

Answer:

[[87]
 [43]
 [90]
 78]]
"""
a[:,:, -2:-1]

array([[[87],
        [43]],

       [[90],
        [78]]])

In [72]:
a[1,0:1,1:3]

array([[78, 90]])

a = np.array(["aasda", "ASDASDASD", "dsadasdsadsadsasasdasadasdasdsadasdsasdasdsadas"],dtype=np.str_)
print(f'Type of array     :" {type(a)}')
print(f'Type of Data      :  {a.dtype}')
print(f'Type of Dimension :" {a.ndim} d array')
print(f'Shape of the Array: {a.shape}')
print(f'Array :\n{a}')

In [111]:
#help(np.array)

In [112]:
l = [3,4,5,6]

In [117]:
b = l.copy()

In [118]:
del b[0]

In [119]:
print(l, id(l))
print(b,id(b))

[4, 5, 6] 5211168192
[5, 6] 5211766400


### View Vs Copy
    - Any changes made to array, will reflect to the view also and  Vice Versa
    - Any change made to array, will not reflect to the copy of array and Vice Versa

In [3]:
a1 = np.array([1,23,4,56,7,89,34])
b1 = a1.copy()
v1 = a1.view()

In [5]:
# Change element at position 1
a1[0] = 42
v1[3] = 5
b1[6] = 63

In [10]:
print(f'Array a1 => Base {a1.base}                    : [{id(a1)}] : {a1} ')
print(f'Copy  b1 => Base {b1.base}                    : [{id(b1)}] : {b1} ')
print(f'View  v1 => Base {v1.base}  : [{id(v1)}] : {v1} ')

Array a1 => Base None                    : [4568158864] : [42 23  4  5  7 89 34] 
Copy  b1 => Base None                    : [4568159824] : [ 1 23  4 56  7 89 63] 
View  v1 => Base [42 23  4  5  7 89 34]  : [4568159248] : [42 23  4  5  7 89 34] 
